import type { BundleTier } from "@prisma/client";

export const BUNDLE_MODULES: Record<BundleTier, string[]> = {
  HORTICULTURE: [
    "field-management",
    "crop-planning",
    "harvest-tracking",
    "pest-spray-log",
    "viticulture",
    "orchard",
    "vegetables",
    "microgreens",
    "protected-cropping",
    "aquaponics",
  ],
  LIVESTOCK: [
    "cattle-dairy",
    "cattle-beef",
    "sheep",
    "goats",
    "deer",
    "pigs",
    "poultry",
    "bees",
    "pasture",
  ],
  FULL: [
    "field-management",
    "crop-planning",
    "harvest-tracking",
    "pest-spray-log",
    "viticulture",
    "orchard",
    "vegetables",
    "microgreens",
    "protected-cropping",
    "aquaponics",
    "cattle-dairy",
    "cattle-beef",
    "sheep",
    "goats",
    "deer",
    "pigs",
    "poultry",
    "bees",
    "pasture",
    "financials",
    "inventory",
    "equipment",
    "weather",
    "compliance",
    "staff",
    "soil-water",
  ],
};
