/**
 * Starter list of widely-known agrichemical products for the Pest & Spray Log
 * "Load standard chemical list" action. Name + active ingredient only — no
 * registration numbers, withholding periods, or hazard classes, since those
 * are product- and jurisdiction-specific and must come from the actual
 * product label, not be guessed here.
 */
export const STANDARD_CHEMICALS: { name: string; activeIngredient: string }[] = [
  // Herbicides
  { name: "Roundup", activeIngredient: "Glyphosate" },
  { name: "Gramoxone", activeIngredient: "Paraquat" },
  { name: "Reglone", activeIngredient: "Diquat" },
  { name: "Amine 600", activeIngredient: "2,4-D" },
  { name: "Tordon", activeIngredient: "Picloram" },
  { name: "Grazon", activeIngredient: "Triclopyr + Picloram" },
  { name: "Versatill", activeIngredient: "Clopyralid" },
  { name: "Buctril", activeIngredient: "Bromoxynil" },
  { name: "Basagran", activeIngredient: "Bentazone" },
  { name: "Atrazine 900", activeIngredient: "Atrazine" },
  { name: "Gesaprim", activeIngredient: "Atrazine" },
  { name: "Simazine 900", activeIngredient: "Simazine" },
  { name: "Diuron 900", activeIngredient: "Diuron" },
  { name: "Hexazinone 250", activeIngredient: "Hexazinone" },
  { name: "Metsulfuron 600", activeIngredient: "Metsulfuron-methyl" },
  { name: "Escort", activeIngredient: "Metsulfuron-methyl" },
  { name: "Chlorsulfuron 750", activeIngredient: "Chlorsulfuron" },
  { name: "Glean", activeIngredient: "Chlorsulfuron" },
  { name: "Terbuthylazine 500", activeIngredient: "Terbuthylazine" },
  { name: "Pendimethalin 440", activeIngredient: "Pendimethalin" },
  { name: "Stomp", activeIngredient: "Pendimethalin" },
  { name: "Trifluralin 480", activeIngredient: "Trifluralin" },
  { name: "Treflan", activeIngredient: "Trifluralin" },
  { name: "Propyzamide 500", activeIngredient: "Propyzamide" },
  { name: "Kerb", activeIngredient: "Propyzamide" },
  { name: "Haloxyfop 520", activeIngredient: "Haloxyfop" },
  { name: "Verdict", activeIngredient: "Haloxyfop" },
  { name: "Fusilade", activeIngredient: "Fluazifop-P-butyl" },
  { name: "Select", activeIngredient: "Clethodim" },
  { name: "Gallant", activeIngredient: "Haloxyfop-R" },
  { name: "Sencor", activeIngredient: "Metribuzin" },
  { name: "Lexone", activeIngredient: "Metribuzin" },
  { name: "Linuron 500", activeIngredient: "Linuron" },
  { name: "Afalon", activeIngredient: "Linuron" },
  { name: "Goal", activeIngredient: "Oxyfluorfen" },
  { name: "Starane", activeIngredient: "Fluroxypyr" },
  { name: "Actril", activeIngredient: "Bromoxynil + MCPA" },
  { name: "MCPA 500", activeIngredient: "MCPA" },
  { name: "Nufarm Banvel", activeIngredient: "Dicamba" },
  { name: "Kamba", activeIngredient: "Dicamba" },
  { name: "Weedmaster Duo", activeIngredient: "Glyphosate" },
  { name: "Sharpen", activeIngredient: "Saflufenacil" },
  { name: "Rango", activeIngredient: "Aminopyralid" },
  { name: "Chikara", activeIngredient: "Flazasulfuron" },
  { name: "Basta", activeIngredient: "Glufosinate-ammonium" },
  { name: "Bastion", activeIngredient: "Glufosinate-ammonium" },
  { name: "Casper", activeIngredient: "Flumioxazin + Carfentrazone-ethyl" },
  { name: "Valor", activeIngredient: "Flumioxazin" },
  { name: "Devrinol", activeIngredient: "Napropamide" },
  { name: "Ronstar", activeIngredient: "Oxadiazon" },

  // Insecticides
  { name: "Lorsban", activeIngredient: "Chlorpyrifos" },
  { name: "Ripcord", activeIngredient: "Cypermethrin" },
  { name: "Ambush", activeIngredient: "Permethrin" },
  { name: "Karate", activeIngredient: "Lambda-cyhalothrin" },
  { name: "Decis", activeIngredient: "Deltamethrin" },
  { name: "Talstar", activeIngredient: "Bifenthrin" },
  { name: "Confidor", activeIngredient: "Imidacloprid" },
  { name: "Admire", activeIngredient: "Imidacloprid" },
  { name: "Actara", activeIngredient: "Thiamethoxam" },
  { name: "Calypso", activeIngredient: "Thiacloprid" },
  { name: "Movento", activeIngredient: "Spirotetramat" },
  { name: "Success", activeIngredient: "Spinosad" },
  { name: "Tracer", activeIngredient: "Spinosad" },
  { name: "Delegate", activeIngredient: "Spinetoram" },
  { name: "Coragen", activeIngredient: "Chlorantraniliprole" },
  { name: "Altacor", activeIngredient: "Chlorantraniliprole" },
  { name: "Proclaim", activeIngredient: "Emamectin benzoate" },
  { name: "Vertimec", activeIngredient: "Abamectin" },
  { name: "Agri-Mek", activeIngredient: "Abamectin" },
  { name: "Rogor", activeIngredient: "Dimethoate" },
  { name: "Malathion 500", activeIngredient: "Malathion" },
  { name: "Fastac", activeIngredient: "Alpha-cypermethrin" },
  { name: "Mavrik", activeIngredient: "Tau-fluvalinate" },
  { name: "Runner", activeIngredient: "Methoxyfenozide" },
  { name: "Intrepid", activeIngredient: "Methoxyfenozide" },
  { name: "Mimic", activeIngredient: "Tebufenozide" },
  { name: "Dominex", activeIngredient: "Alpha-cypermethrin" },
  { name: "Metafos", activeIngredient: "Methomyl" },
  { name: "Lannate", activeIngredient: "Methomyl" },
  { name: "Steward", activeIngredient: "Indoxacarb" },
  { name: "Avatar", activeIngredient: "Indoxacarb" },
  { name: "Pirimor", activeIngredient: "Pirimicarb" },
  { name: "Aphidex", activeIngredient: "Pirimicarb" },
  { name: "Applaud", activeIngredient: "Buprofezin" },
  { name: "Trigard", activeIngredient: "Cyromazine" },
  { name: "Sumithion", activeIngredient: "Fenitrothion" },
  { name: "Diazinon 800", activeIngredient: "Diazinon" },
  { name: "Attack", activeIngredient: "Diazinon" },
  { name: "Bugmaster", activeIngredient: "Carbaryl" },
  { name: "Sevin", activeIngredient: "Carbaryl" },
  { name: "Thiodan", activeIngredient: "Endosulfan" },
  { name: "Danitol", activeIngredient: "Fenpropathrin" },
  { name: "Movento Energy", activeIngredient: "Spirotetramat + Imidacloprid" },
  { name: "Transform", activeIngredient: "Sulfoxaflor" },
  { name: "Closer", activeIngredient: "Sulfoxaflor" },
  { name: "Verimark", activeIngredient: "Cyantraniliprole" },
  { name: "Exirel", activeIngredient: "Cyantraniliprole" },
  { name: "Beleaf", activeIngredient: "Flonicamid" },
  { name: "DDVP 1000", activeIngredient: "Dichlorvos" },
  { name: "Neem Oil", activeIngredient: "Azadirachtin" },
  { name: "Eco-Oil", activeIngredient: "Botanical oil blend" },
  { name: "Pyrethrum", activeIngredient: "Pyrethrins" },
  { name: "BT Kurstaki", activeIngredient: "Bacillus thuringiensis" },
  { name: "Dipel", activeIngredient: "Bacillus thuringiensis" },

  // Fungicides
  { name: "Mancozeb 800", activeIngredient: "Mancozeb" },
  { name: "Dithane", activeIngredient: "Mancozeb" },
  { name: "Penncozeb", activeIngredient: "Mancozeb" },
  { name: "Bravo", activeIngredient: "Chlorothalonil" },
  { name: "Echo", activeIngredient: "Chlorothalonil" },
  { name: "Captan 800", activeIngredient: "Captan" },
  { name: "Orthocide", activeIngredient: "Captan" },
  { name: "Copper Oxychloride", activeIngredient: "Copper oxychloride" },
  { name: "Kocide", activeIngredient: "Copper hydroxide" },
  { name: "Champ", activeIngredient: "Copper hydroxide" },
  { name: "Bordeaux Mixture", activeIngredient: "Copper sulfate + Lime" },
  { name: "Nordox", activeIngredient: "Cuprous oxide" },
  { name: "Carbendazim 500", activeIngredient: "Carbendazim" },
  { name: "Bavistin", activeIngredient: "Carbendazim" },
  { name: "Score", activeIngredient: "Difenoconazole" },
  { name: "Amistar", activeIngredient: "Azoxystrobin" },
  { name: "Cabrio", activeIngredient: "Pyraclostrobin" },
  { name: "Cabrio Top", activeIngredient: "Pyraclostrobin + Metiram" },
  { name: "Folicur", activeIngredient: "Tebuconazole" },
  { name: "Orius", activeIngredient: "Tebuconazole" },
  { name: "Prosaro", activeIngredient: "Prothioconazole + Tebuconazole" },
  { name: "Proline", activeIngredient: "Prothioconazole" },
  { name: "Rovral", activeIngredient: "Iprodione" },
  { name: "Sumisclex", activeIngredient: "Procymidone" },
  { name: "Ronilan", activeIngredient: "Vinclozolin" },
  { name: "Switch", activeIngredient: "Cyprodinil + Fludioxonil" },
  { name: "Teldor", activeIngredient: "Fenhexamid" },
  { name: "Rovral Aquaflo", activeIngredient: "Iprodione" },
  { name: "Ridomil Gold", activeIngredient: "Metalaxyl-M + Mancozeb" },
  { name: "Fongarid", activeIngredient: "Furalaxyl" },
  { name: "Aliette", activeIngredient: "Fosetyl-aluminium" },
  { name: "Previcur", activeIngredient: "Propamocarb" },
  { name: "Curzate", activeIngredient: "Cymoxanil" },
  { name: "Fubol Gold", activeIngredient: "Metalaxyl-M + Mancozeb" },
  { name: "Nativo", activeIngredient: "Trifloxystrobin + Tebuconazole" },
  { name: "Flint", activeIngredient: "Trifloxystrobin" },
  { name: "Systhane", activeIngredient: "Myclobutanil" },
  { name: "Rally", activeIngredient: "Myclobutanil" },
  { name: "Topas", activeIngredient: "Penconazole" },
  { name: "Bumper", activeIngredient: "Propiconazole" },
  { name: "Tilt", activeIngredient: "Propiconazole" },
  { name: "Bayfidan", activeIngredient: "Triadimenol" },
  { name: "Sportak", activeIngredient: "Prochloraz" },
  { name: "Sulphur 800 WG", activeIngredient: "Sulphur" },
  { name: "Kumulus", activeIngredient: "Sulphur" },
  { name: "Thiram 800", activeIngredient: "Thiram" },
  { name: "Serenade", activeIngredient: "Bacillus subtilis" },
  { name: "Trichoflow", activeIngredient: "Trichoderma spp." },

  // Adjuvants, plant growth regulators & other
  { name: "Pulse Penetrant", activeIngredient: "Organosilicone surfactant" },
  { name: "BS1000", activeIngredient: "Non-ionic surfactant" },
  { name: "Uptake Spraying Oil", activeIngredient: "Petroleum oil" },
  { name: "Du-Wett", activeIngredient: "Organosilicone surfactant" },
  { name: "LI-700", activeIngredient: "Lecithin + Propionic acid" },
  { name: "Sylgard 309", activeIngredient: "Organosilicone surfactant" },
  { name: "Actiwett", activeIngredient: "Non-ionic surfactant" },
  { name: "Freeway", activeIngredient: "Non-ionic surfactant blend" },
  { name: "ProGibb", activeIngredient: "Gibberellic acid" },
  { name: "Regalis", activeIngredient: "Prohexadione-calcium" },
  { name: "Retain", activeIngredient: "Aminoethoxyvinylglycine (AVG)" },
  { name: "Cultar", activeIngredient: "Paclobutrazol" },
  { name: "Ethrel", activeIngredient: "Ethephon" },
  { name: "SmartFresh", activeIngredient: "1-Methylcyclopropene" },
  { name: "Slug Out", activeIngredient: "Metaldehyde" },
  { name: "Baysol", activeIngredient: "Metaldehyde" },
  { name: "Slugout Ferric", activeIngredient: "Ferric phosphate" },
  { name: "Ratsak", activeIngredient: "Brodifacoum" },
  { name: "Pindone", activeIngredient: "Pindone" },
  { name: "Talon", activeIngredient: "Brodifacoum" },
  { name: "Feracol", activeIngredient: "Cholecalciferol" },

  // Additional herbicides
  { name: "Torpedo", activeIngredient: "Glyphosate" },
  { name: "Credit", activeIngredient: "Glyphosate" },
  { name: "Buster", activeIngredient: "Glufosinate-ammonium" },
  { name: "Logran", activeIngredient: "Triasulfuron" },
  { name: "Ally", activeIngredient: "Metsulfuron-methyl" },
  { name: "Harmony", activeIngredient: "Thifensulfuron-methyl" },
  { name: "Broadstrike", activeIngredient: "Flumetsulam" },
  { name: "Spinnaker", activeIngredient: "Imazethapyr" },
  { name: "Raptor", activeIngredient: "Imazamox" },
  { name: "Amicide", activeIngredient: "2,4-D Amine" },
  { name: "Estercide", activeIngredient: "2,4-D Ester" },
  { name: "Preside", activeIngredient: "Flumetsulam + Metosulam" },
  { name: "Diflufenican 500", activeIngredient: "Diflufenican" },
  { name: "Brodal", activeIngredient: "Diflufenican" },
  { name: "Barrel", activeIngredient: "2,4-D + Picloram" },
  { name: "Nuquat", activeIngredient: "Paraquat" },

  // Additional insecticides
  { name: "Nemesis", activeIngredient: "Fipronil" },
  { name: "Regent", activeIngredient: "Fipronil" },
  { name: "Termidor", activeIngredient: "Fipronil" },
  { name: "Warrior", activeIngredient: "Lambda-cyhalothrin" },
  { name: "Hallmark", activeIngredient: "Lambda-cyhalothrin" },
  { name: "Bathrick", activeIngredient: "Bifenthrin" },
  { name: "Chess", activeIngredient: "Pymetrozine" },
  { name: "Plenum", activeIngredient: "Pymetrozine" },
  { name: "Movento 240", activeIngredient: "Spirotetramat" },
  { name: "Oberon", activeIngredient: "Spiromesifen" },
  { name: "Envidor", activeIngredient: "Spirodiclofen" },
  { name: "Kanemite", activeIngredient: "Acequinocyl" },
  { name: "Nissorun", activeIngredient: "Hexythiazox" },
  { name: "Magister", activeIngredient: "Fenazaquin" },
  { name: "Insegar", activeIngredient: "Fenoxycarb" },
  { name: "Gazelle", activeIngredient: "Acetamiprid" },
  { name: "Mospilan", activeIngredient: "Acetamiprid" },

  // Additional fungicides
  { name: "Custodia", activeIngredient: "Azoxystrobin + Tebuconazole" },
  { name: "Priori Gold", activeIngredient: "Azoxystrobin + Difenoconazole" },
  { name: "Opus", activeIngredient: "Epoxiconazole" },
  { name: "Rubric", activeIngredient: "Epoxiconazole" },
  { name: "Aviator Xpro", activeIngredient: "Bixafen + Prothioconazole" },
  { name: "Elatus", activeIngredient: "Benzovindiflupyr + Azoxystrobin" },
  { name: "Miravis", activeIngredient: "Pydiflumetofen" },
  { name: "Luna Experience", activeIngredient: "Fluopyram + Tebuconazole" },
  { name: "Luna Sensation", activeIngredient: "Fluopyram + Trifloxystrobin" },
  { name: "Vivando", activeIngredient: "Metrafenone" },
  { name: "Legend", activeIngredient: "Fluazinam" },
  { name: "Shirlan", activeIngredient: "Fluazinam" },
  { name: "Emerald", activeIngredient: "Boscalid" },
  { name: "Filan", activeIngredient: "Boscalid" },
  { name: "Signum", activeIngredient: "Boscalid + Pyraclostrobin" },
];
